# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:

  sourcingdb:
    container_name: sourcingdb
    restart: always
    volumes: 
      - /usr/local/mongodb:/todo
      #- .data:/data/db
    ports: 
      - "27017:27017"

      
  eshopproducts:
    image: eshopproducts
    build:
      context: .
      dockerfile: src/EShopMicroService/EShop.Products/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - "ProductDatabaseSettings:ConnectionString=mongodb://sourcingdb:27017"
    depends_on: 
      - sourcingdb
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
    ports:
      - "8076:80"
